services:
  db:
    image: mysql:8.0
    container_name: fizy-mysql
    environment:
      MYSQL_ROOT_PASSWORD: XYZgs14531071.  # Sadece bunu kullan!
      MYSQL_DATABASE: fizy
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: fizy-app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: XYZgs14531071.
      MYSQL_DB: fizy
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
